theme: jekyll-theme-architect
title: Welcome to my blog

#Blog

##Programming Languages and Technologies
PHP, AngularJS, Javascript, JQuery, AJAX, JSON, HTML, CSS, Bootstrap.

### This project runs on localhost with PHPMyAdmin DB.
